### PR TITLE
ASDF definitions + documentation

### PR DESCRIPTION
**Pull request by christophejunke**
- Declare test operations from ASDF
- AFAIK, the separate package for the system file is not necessary
- Update documentation

### CODE REVIEW

**Comment by marijnh** [comment]
Thanks! If you want, I'll gladly give you access to this repo, since I don't really maintain it myself anymore.

**Comment by christophejunke** [comment]
Thanks, I'd be happy to help maintain this project.

**Comment by marijnh** [comment]
Cool. Did you see the invite (https://github.com/marijnh/ieee-floats/invitations)?

**Comment by christophejunke** [comment]
Didn't see it before you send the message, thanks.

**Comment by quicklisp** [comment]
This change breaks building with the latest SBCL and ASDF 3.1.5. I get an illegal function call error in the test-op clause in the system file. Is this change intended for some newer or older version of ASDF?

**Comment by christophejunke** [comment]
The change was meant to introduce test operations to the system. Unfortunately, there was a typo (see https://github.com/marijnh/ieee-floats/commit/ab256451a357063b5b8706aaabdb18196687cdbb). Sorry for the inconvenience. I cleared the cache and compiled the library again from a fresh execution of sbcl, then executed successfully `(asdf:test-system :ieee-floats)`. If however it still breaks in your environment, we can revert to the previous version.

**Pull request merged**
